### ISSUE TITLE
Feature request: Custom command plugins

### ISSUE THREAD

**Issue by pinpox** [friedow/centerpiece#156]
It would be nice to have a generic "custom" plugin, that let's you configure a bash command to create a list and a bash command to act on the selection. This could be useful for a number of cases, I have included two examples as configuration format proposal below.

```yaml
plugin:
  applications:
    enable: true
# ... 
  cusom:
    enable: true
    commands:
      - name: "Open code project"
        command: "ls -l ~/code"
        action: "foot --working-derectory ~/code/{}"
      - name: "Mail contact"
        command: "cat ~/mail-addresses.txt"
        action: "neomutt -s 'mail from centerpiece' {}"
# ...
  
```

In the configuation of each instance of the `command` should return a list of strings separted by newline and `action` should be a bash command to execute when pressing enter on a selection. Of course there needs to be some predefined placeholder (here `{}` e.g.) that get's interpolated into the command string.
